listen_addresses = '*'
max_connections = 100
shared_buffers = 128MB
effective_cache_size = 512MB
work_mem = 4MB
maintenance_work_mem = 64MB
wal_level = replica
password_encryption = 'scram-sha-256'
log_connections = on
log_disconnections = on
